### ISSUE TITLE
Dynamic recompilers creating problems in Zaxxon's Motherbase 2000

### ISSUE THREAD

**Issue by randombyt** [notaz/picodrive#104]
If the option "dynamic recompilers" is turned on (default state) Zaxxon is unplayable as the sprites are not visible/ glitched. It works fine if dynamic recompilers option is turned off. This is on RetroArch windows OS.

Dynamic recompilers on:
![Zaxxon's Motherbase 2000 (USA)-200124-163422](https://user-images.githubusercontent.com/43263155/73066340-87718800-3ec7-11ea-9aee-ca5c39bd6579.png)

Dynamic recompilers off:
![Zaxxon's Motherbase 2000 (USA)-200124-163400](https://user-images.githubusercontent.com/43263155/73066389-9f490c00-3ec7-11ea-8ede-c8aade4a7f12.png)

Note: In the titles I have tested, this issue only exists on Zaxxon. Other titles work as intended with DR option turned on.

**Comment by PhatHub** [comment]
I can confirm I'm encountering this with Retropie on x86-64. 

- The initial startup the polygons will be missing and the background does not move/progress. The ship is represented by a red dot. The "Stage 1 Ready" message is replaced with a white screen.

- If I turn off Dynamic Recompiling before restarting picodrive, the action will be very slow with audio errors.

- Then when I turn Dynamic Recompiling back on (without restarting picodrive), the graphics are still normal, and there is no slowdown or audio jitter.

**Comment by irixxxx** [comment]
Should be fixed in my irixxxx/picodrive repo

**Comment by randombyt** [comment]
Thanks! working as expected now, no more graphical distortions. Closing the issue.
