### ISSUE TITLE
DS(i) Port

### ISSUE THREAD

**Issue by NightScript370** [notaz/picodrive#116]
Back on June 3rd-4th 2006, someone made a port of PicoDrive to the Nintendo DS platform. Since then, PicoDrive has advanced quite a bit to the point of getting Sega CD and other things working. However, the original dev quit working on it and no one took up the job of updating PicoDriveDS to the latest PicoDrive version.

I was wondering if it was possible to port the latest PicoDrive version to the Nintendo DS, or at least to find the source code from June 3rd-4th so I could try to update it on my own.

**Comment by gameblabla** [comment]
There was an attempt to update the Picodrive port but even that was discontinued later :
https://github.com/bubble2k16/picodrive_3ds/releases

And you must have been thinking of this port attempt
https://github.com/ryanfb/picodriveds

**Comment by NightScript370** [comment]
This is a late response (sorry) but thanks for pointing me in the right direction. We tried to update it for the TWL environment, meaning that its been beneficial.
Closing.
