### ISSUE TITLE
[PocketGo2 v2 / PicoDrive 1.95] Random freezes in 32X games

### ISSUE THREAD

**Issue by Drumaster78** [notaz/picodrive#117]
Hardware: PocketGo2 v2
O/S: Rogue FW 1.0.9 for PocketGo2 v2
Software: PicoDrive 1.95 (recompiled by gameblabla with irixxxx's 32X MIPS core found here: https://gameblabla.nl/files/ipk/gcw0/picodrive_gcw0.opk)
ROM: Virtua Racing Deluxe (Japan) 32X version

Get some random freezes ingame or in the menu in Virtua Racing Deluxe Japanese version. I found absolutely no way to reproduce it efficiently, I just played and it happened sometimes.
I attached 2 savestates saved during 2 different freezes (as the emulator is still working), so maybe you can have some logs or something from a debug version of the emulator.

[Savestates_freezes_Virtua Racing Deluxe (Japan).zip](https://github.com/notaz/picodrive/files/5194273/Savestates_freezes_Virtua.Racing.Deluxe.Japan.zip)

**Comment by irixxxx** [comment]
please close this, it is not related to this repo.

**Comment by Drumaster78** [comment]
You're right. Closed.
