### ISSUE TITLE
Impossible to compile for PSP

### ISSUE THREAD

**Issue by Jacksoft** [notaz/picodrive#122]
Hi,
I've successifully installed pspdev and sdk under linux (WSL). When I launch the make it halts on "common" missing files. If I manually fix the missing filenames (menu_pico.h, input_pico.h and others) it gives a TONS of errors on emu.c and it's pratically uncompilable.
![picodrive](https://user-images.githubusercontent.com/5840483/103217915-0b26c680-491a-11eb-9d9e-b51441d097f6.png)

**Comment by notaz** [comment]
The official PSP port was abandoned in 2007 or so. I heard there are forks that fixed it, but it's up to you to find them.
