### ISSUE TITLE
retroarch: lost vikings colors are RGB-swapped

### ISSUE THREAD

**Issue by thesourcehim** [notaz/picodrive#127]
The image is red/blue swapped.

**Comment by irixxxx** [comment]
What hardware have you used? With which lr-picodrive version?
BTW, I've just fixed a color swap on psp in the lr-picodrive repo.

**Comment by thesourcehim** [comment]
I use Sony PSP. I'll try their new nightly version then.

**Comment by thesourcehim** [comment]
Fixed in latest nightly build.
