### ISSUE TITLE
Missing license information for fame

### ISSUE THREAD

**Issue by orbea** [notaz/picodrive#132]
@notaz 

Do you know what the license information for `cpu/fame/` is? The only thing I can find anywhere is the following line, but the relevant html file that should of had license information is long gone.

https://github.com/notaz/picodrive/blob/1d366b1ad9362fd463c42979c8a687dfc7f46c46/cpu/fame/fame.h#L6

**Comment by irixxxx** [comment]
Get it here: http://www.emu-france.com/emulateurs/7-processeurs/82-680x0/2311-fame/

**Comment by orbea** [comment]
Thanks, that has the terms of use.

> FAME may be distributed freely in unmodified form, as long as this document file is included.
>
>Nothing may be charged for this library. If you want to use it in a shareware or commercial application, contact me.
>
>The author will not be held liable for damages. FAME comes with absolutely NO WARRANTY. Anyway i will try to help you with >any problem you have using FAME.
>
>If you do not agree with all of these terms, please remove FAME from your computer.
>
>You are encouraged to contact the author if you wish to use FAME in a commercial product (to negotiate licensing).
>
>Any program which uses FAME must include in its documentation or in the program itself the following credit text:
>
>FAME Motorola 68000 Emulation Library by Oscar Orallo (oscar@m68k.com)
