### ISSUE TITLE
[32x] It feels to me that Sega 32x have 3d rendering core

### ISSUE THREAD

**Issue by WhiteMagicRaven** [notaz/picodrive#138]
If so its is true?
Can it be in distant future , in theory, upscale 3d like bsnes do it for mode 7 ?

**Comment by irixxxx** [comment]
I'd say no, it can't. The VDP in the 32X doesn't have any scaling/rotation/3D hardware. Only emulation of such a hardware would IMO allow for general rendering or filtering at a higher resolution.

**Comment by WhiteMagicRaven** [comment]
Well 
the  games like
Metal Head
and
Virtua Racing Deluxe
the cartridges with this games comes with additional 3d chip on own cartridge?

by reading wikipedia i get confused here
https://en.wikipedia.org/wiki/32X#Development
https://en.wikipedia.org/wiki/Sega_Genesis#Sega_Virtua_Processor
https://en.wikipedia.org/wiki/Sega_Genesis#Sega_32X

it tells that it has limited 3d capabilities

**Comment by irixxxx** [comment]
No, AFAIK there is no 3D hardware in any 32X game. All the 3D calculations are done in software on one or both of the 32X CPUs.

**Comment by WhiteMagicRaven** [comment]
ok, thank you very much! I am sorry to disturb you, now close it.
