### ISSUE TITLE
Audio problems in Sonic 1 and 2 Genesis

### ISSUE THREAD

**Issue by RobotLimeLtd** [notaz/picodrive#158]
Since upgrading to version 2.0.0, I’ve had problems with the original Sonic The Hedgehog and Sonic The Hedgehog  2 on Sega Genesis.

Under the 2.0.0-alpha release, Sonic 2 would frequently boot with no “Sega” audio at the start, and then no music in-game (but sound effects still working).  In the beta2-ad93670 release, there’s no audio at all - the game is completely silent.

In Sonic The Hedgehog (original Japanese version) there are sometimes audio problems in the Marble Zone where one of the sound channels (the one that does the high pitched part of the tune - not sure if it’s FM or PSG) isn’t working.  This seems to happen when resuming from a save state.

Both games are fine in other emulator cores.

**Comment by irixxxx** [comment]
Can be closed here. fixed in my repo by 274dd51.
