### ISSUE TITLE
[32X] Sonic Robo Blast 2 0.1a (fangame)

### ISSUE THREAD

**Issue by dxgldotorg** [notaz/picodrive#162]
Sonic Robo Blast 2 32X ([https://ssntails.srb2.org/srb32x/](url)) does not run properly on PicoDrive libretro core, with the level start animation in very slow motion and the gameplay itself very slow too, as slow as under 1 frame per second.  The game clock increments at an unusually fast rate, racking up 30+ minutes in short order.

While the demo is not intended for any emulators other than Kega Fusion or as of version 0.1a Ares, this might in itself reveal an inaccuracy in PicoDrive's emulation as it does run correctly on real hardware and Kega Fusion.

Also applies to 0.1 but 0.1a had come out before I completed writing this Issue so I tested that first.

**Comment by notaz** [comment]
@irixxxx confirmed it runs on my hw and is broken in PD, even my old versions before you took over. I strongly suspect it's the SH2 WDT because if you force it to 0, the game animations are no longer stuck (but ingame logic and the onscreen timer doesn't progress).
