### ISSUE TITLE
Broken fade-to-black effect on Golden Axe (World)

### ISSUE THREAD

**Issue by vanfanel** [notaz/picodrive#18]
After the Tyris Flare (Amazon) demo part in attract mode, the fade-to-black effect is broken. It shows corrupt pink tiles instead of the expected black ones.
Maybe a palette issue? The rest of the attract mode is fine.

**Comment by vanfanel** [comment]
There are more problems with attract mode in Golden Axe, but they only appear in ROM version V1.1:
-There's a strange sound playing along the scream of the fallen enemy on Ax Battler attract sequence.
-There's the aforementioned "pink" corrupt graphics when Tyris Flare attractc sequence ends.
I am attaching an screen capture so you can see what I mean.
The strange part is that these problems ONLY appears on ROM version 1.1, and original world version is not affected.

![2015-10-22-154252_642x507_scrot](https://cloud.githubusercontent.com/assets/837585/10666788/15cfb590-78d4-11e5-86d4-9ea713df8bb5.png)

**Comment by vanfanel** [comment]
Since this error appears no matter what CPU emulation core is used, and it doesn't seem to be an CDP error, it's caused by the parameters the emulator passes to the CPU core.
Setting #define CYCLES_M68K_LINE to 530 on pico_cmn.c makes the error go away. However this is clearly a hack: so this seems that this is a patched PAL rom (or an NTSC rom with PAL code somewhere) that needs more M68K cycles per line than expected for an NTSC game...
Discurssion in spanish here:
http://www.elotrolado.net/hilo_diferencias-entre-la-rom-original-de-golden-axe-de-megadrive-y-la-version-1-1_2130646

Thanks to TheElf for the ideas.

**Comment by notaz** [comment]
I'm no longer seeing this in the git version, so assuming fixed.
