### ISSUE TITLE
Cannot compile picodrive on Debian Jessie

### ISSUE THREAD

**Issue by kalehrl** [notaz/picodrive#25]
Hello notaz
I'm unable to compile picodrive on Debian Jessie.
The error I get is:

80 -c -o cpu/fame/famec.o cpu/fame/famec.c
cc: internal compiler error: Killed (program cc1)
Please submit a full bug report,
with preprocessed source if appropriate.
See file:///usr/share/doc/gcc-4.9/README.Bugs for instructions.
: recipe for target 'cpu/fame/famec.o' failed
make: *** [cpu/fame/famec.o] Error 4

I'm using Makefile.libreto becuase I want to use retroarch.
I successfully compiled several cores and retroarch.
Do you have any ideas what may be causing it?
Thank you

**Comment by kalehrl** [comment]
I solved it by assigning 2GB of RAM to the virtual machine.
I had 1GB previously which wasn't enough.
Compiling this core is very demanding.
Please mark as solved.

**Comment by notaz** [comment]
Yeah compilers often have trouble with fame..
