### ISSUE TITLE
bad autodetection of OSS in linux

### ISSUE THREAD

**Issue by mckaygerhard** [notaz/picodrive#30]
the configure script make bad autodetection of the OSS framework installed, assumed that OSS are series 4 and in my linux i have 2 installed (the most older previous to alsa migration)

so build in linux must disable explicit the oss driver from list when are those cases

i dont know if that issue are here or for the libpicofe library.

```
platform/libpicofe/linux/sndout_oss.c: In function ‘sndout_oss_wait’:
platform/libpicofe/linux/sndout_oss.c:181: error: ‘SOUND_PCM_SYNC_is_obsolete_use_SNDCTL_DSP_SYNC_instead’ undeclared (first use in this function)
platform/libpicofe/linux/sndout_oss.c:181: error: (Each undeclared identifier is reported only once
platform/libpicofe/linux/sndout_oss.c:181: error: for each function it appears in.)
make: *** [platform/libpicofe/linux/sndout_oss.o] Error 1

```

**Comment by notaz** [comment]
Should be fixed (don't forget git submodule update).
