### ISSUE TITLE
license and redistribution nonsense, due conlficts clauses respect supported

### ISSUE THREAD

**Issue by mckaygerhard** [notaz/picodrive#32]
i read the license file after several compilation/testing times and a fail intent of packagin (due home user issues not xdg compatible)

noted licence have some limitations so emulator may or may not are compatible with GPL due the 1rs section that dont allow commercial usage...

so if this are true, i request removal of mocofost guindows spport due i noted picodrive can be compiled and use on mocosoft guindows... when and commercial os with EULA license are under a machine, the usage are not personal, are "temporal until enterice decides to upgrade or cut support", user are not own of the software and contents, only can made "usage of all and contents"

***so the license are illogical due permit "not in literal" commecial usage when user sold the machine with orginal OS and includes the picodrive inside!***

the 3rd clause are not relevant, and may in that case are ilogically repect the firts!

NOW IN PARTICULAR i like the license, du permits removal of guindo like support.

**if that are not like for any of development, i note that license are only a fake and redistribution are assumed!**

after a possitive response, wait for some pull by me..in other way its a good emulator, but the license are **nonsense due commercial redistribution are assumed if are inside a commercial product**

**Comment by notaz** [comment]
PicoDrive uses portions of MAME code, so the license is MAME and I can not change it. And before you ask, no I don't have time to rewrite MAME code.
http://mamedev.org/legal.html

**Comment by mckaygerhard** [comment]
asw i suspect.. u never will remove windose code, this will implics remove also support for handled commercial devices..

mame are so far different:, u'r license said "**nor** may they be used in a **commercial
 product or activity**" and the mame license said "with permision of author" so u'r license are so far different literally are ilogicalli and i assume that! so i will assume my "products are like a os windo and if i sold i'm not break u'r license" so in teory i can redistribute , u'r are notified.

**Comment by mckaygerhard** [comment]
PD: the mame license u link are a part only... see the code.

**Comment by Oggom** [comment]
@mckaygerhard https://github.com/mamedev/mame/blob/master/docs/mamelicense.txt#L15

**Comment by mckaygerhard** [comment]
mame its a trademark, picodrive not

**Comment by carlospea** [comment]
Mame license has changed much since its provisions, due so many commercial derived implicit usage,  were somewhat incongruous, so result today is that this migrating to gpl: https://github.com/mamedev/mame#license

The example has some point to take, i have WindowsXP with picodrive installed, and i sold my computer with picodrive still installed, now i violated the license, but at first install i not violate due at install moment gon to use only for gaming and so was not violated.

**Comment by Oggom** [comment]
@carlospea What kind of license MAME is using these days doesn't matter as it was still non-commercial when the code was brought to PicoDrive.
If you really need to use a GPL'd Mega Drive emulator, why not use Gens or mednafen instead?
Also, you really didn't need to create another account just to post this.

**Comment by carlospea** [comment]
I you want my mail or facebook to confirm i'm not mckaygerhard, tell me where, in any case i'ts your decision
