### ISSUE TITLE
Desynchronized border in Golden Axe 3 

### ISSUE THREAD

**Issue by vanfanel** [notaz/picodrive#33]
Hi,

This game shows a noticeable error on the tittle screen, where the fast-moving background has a vertical border which seems "unaligned" with the rest of the screen are. It's way easier to see it in movement:

![2015-10-25-125456_642x507_scrot](https://cloud.githubusercontent.com/assets/837585/10715489/9a53bb18-7b18-11e5-9e93-4260d9eb2463.png)

Any idea on what could be causing this? I have been fiddling with cycles per line, etc... but it remains there. CPU emulation and VDP seems to be pretty much spot on, so I doubt that's the case.
Chosing the "8bit fast" renderer makes the deffect go away, so... is it something present on real HW that PicoDrive emulates faithfully or a problem with the "16bit accurate" renderer?

**Comment by notaz** [comment]
Finally fixed in 1.92, was a problem in drawing code.
