### ISSUE TITLE
GCW Zero: Sega CD

### ISSUE THREAD

**Issue by zippyjake** [notaz/picodrive#36]
Hi. When loading a Sega CD iso that is EU is said I don't have any bios what should I do?

**Comment by Oggom** [comment]
Well, do you have a PAL Mega CD BIOS?

It should be named "bios_CD_E.bin".

**Comment by zippyjake** [comment]
Where should I put it then

**Comment by zippyjake** [comment]
can you just please tell me how to work the Sega cd Part with the bios

**Comment by notaz** [comment]
Sounds like a configuration issue.
