### ISSUE TITLE
32x layer not show in PSP

### ISSUE THREAD

**Issue by robson-alcantara** [notaz/picodrive#39]
Dear, I made a PicoDrive port for the PSP , but the 32X layer is not being displayed (as if the PicoDraw32xLayer function not to take effect) . Any suggestions?

**Comment by notaz** [comment]
It has been many years since I worked on it, I don't remember anything and can't help you, sorry.

32X will be too slow on PSP anyway, is there any point doing it?

**Comment by robson-alcantara** [comment]
Maybe yes, maybe not. The optimization can wait. Look this: https://www.youtube.com/watch?v=p_rTCy2Rb88

**Comment by robson-alcantara** [comment]
I sold, the line:

PicoDrawSetOutBuf((unsigned short *)VRAM_CACHED_STUFF + 8, 512 );

was missing in emu.c
