### ISSUE TITLE
Rendering Issue Toe Jam & Earl

### ISSUE THREAD

**Issue by Breadwinka** [notaz/picodrive#40]
As you can see the Earthling is rendering over your hud. Which is not correct.
![image](https://cloud.githubusercontent.com/assets/13487931/17238642/6576246a-552b-11e6-9267-b6b0a0937c90.png)

**Comment by dankcushions** [comment]
fairly sure this happens on the original hardware

**Comment by Breadwinka** [comment]
it does not happen on original hardware.

https://youtu.be/nJHKkkarGSw?t=2284

**Comment by notaz** [comment]
Fixed in 1.92.
