### ISSUE TITLE
pier solar on PSP

### ISSUE THREAD

**Issue by tngustavo** [notaz/picodrive#44]
Can't run pier solar on PSP Picodrive, it won't go beyond the first text screen. The only picodrive version I could make pier solar runs was the robson-alcantara's 1.91, but with graphics glitchs. I opened an issue on that branch, but he said the pier solar work is probably thanks to your version, right? 

The issues I found on 1.91 was:
"There are graphics glitchs in the characters, as soon as you leave the house and meet the first friend. Also other characters outside have messed up graphics."

Thanks

**Comment by notaz** [comment]
Yes it triggers general VDP emulation bugs. Don't know if/when I can work on fixing it.

**Comment by tngustavo** [comment]
I'm not aware about VDP, sorry. 
If you could do some work on that someday, please, let me know.

Thanks!

**Comment by tngustavo** [comment]
The glitchs appear to be wrong sprites on characters, maybe just wrong data/table for the sprites or wrong location was read.

**Comment by dinkc64** [comment]
I ran into this problem with my megadrive emulator before, its not related to picodrive but I have some info that might help:
in my emulator, it was dmaing data from the flat rom, but, with pier solar it needs to dma data from banked rom data.  a very simple change.  Just make dma respect banked data :)

**Comment by tngustavo** [comment]
Wish I could change that, but I never worked on an emulator before, have no
idea where to begin. :(

2017-09-03 10:43 GMT-03:00 dinkc64 <notifications@github.com>:

**Comment by robson-alcantara** [comment]
Maybe I can help

**Comment by notaz** [comment]
> in my emulator, it was dmaing data from the flat rom, but, with pier solar it needs to dma data from banked rom data. a very simple change. Just make dma respect banked data :)

True, I was surprised I had it wrong (code from me from years ago is like code from a different person).

I have a fix but I want to finish some other things before I push.

**Comment by tngustavo** [comment]
That sounds great notaz! I was waiting for that.
Could you answer this topic when you release that version?
I can test the pier solar on psp and pay you some beers or coffees.

Thanks!

2017-09-26 6:12 GMT-03:00 notaz <notifications@github.com>:

**Comment by notaz** [comment]
I've pushed out the code, however I no longer maintain the PSP port, so whomever is still doing PSP releases needs to update to newer code.
