### ISSUE TITLE
Some feedback on the Windows (Win32 in this case) port of PicoDrive...

### ISSUE THREAD

**Issue by John-Enigma** [notaz/picodrive#49]
I just downloaded this emulator for the first time to see how it is, and I now I'm gonna leave some feedback: 

1. Whenever I start the emulator, it would automatically open a ROM finder. Most emulators that I know don't do that at all. 

2. And even when I try to search for ROM's, it doesn't detect .md (Mega Drive) files. It only asks me to find ROM's but that's it. It doesn't detect Genesis ROM's at all, despite the fact that, in part, this is also a Genesis emulator. 

3. Why is Pico grayed out?

3. In the readme that I received from this emulator you said this:

> The sole purpose of this port is to demonstrate my SVP and Sega Pico emulation
code. This makes it one of the most minimal emulators out there. If you need
more features, you will have to wait until support is integrated in Kega,
Gens and the likes, as this emu was not meant to compete with them. 

However, I'm noticing that this port is severely lacking so many features that the other ports (like UIQ, GP2X, Pandora, and PSP, between others) have. It doesn't even have the support of SG-1000/SC-3000/SF-7000, Master System, Game Gear, or Genesis/32X/CD. In my honest opinion, this emulator shouldn't rely on Sega Pico support only. 

Also, honest question: from time to time, how long does this emulator get updated on this Github page? Because, from the looks of it, it usually takes like a year or two to update. 

Thank you for reading this. 

EDIT: I downloaded the emulator from here: http://notaz.gp2x.de/pico.php

**Comment by notaz** [comment]
Hmm you're giving feedback on a 9 year old build? I even forgot it existed, not to mention why I made it in the first place. It's pretty safe to say it won't be ever updated.

**Comment by John-Enigma** [comment]
Why does this emulator doesn't have Windows OS support?
