### ISSUE TITLE
Build fails against system zlib.h Ubuntu 17.04 64-bit

### ISSUE THREAD

**Issue by noabody** [notaz/picodrive#51]
pico/cart.c:52:12: error: conflicting types for ‘uncompress2’
 static int uncompress2(void *dest, int destLen, void *source, int sourceLen)
            ^~~~~~~~~~~
In file included from pico/cart.c:13:0:
/usr/include/zlib.h:1283:21: note: previous declaration of ‘uncompress2’ was here
 ZEXTERN int ZEXPORT uncompress2 OF((Bytef *dest,   uLongf *destLen,
                     ^~~~~~~~~~~
<builtin>: recipe for target 'pico/cart.o' failed

```
./configure 
architecture        x86_64
platform            generic
sound drivers        oss alsa sdl
C compiler          gcc
C compiler flags     -I/usr/include/SDL -D_GNU_SOURCE=1 -D_REENTRANT -Wno-unused-result
libraries           -L/usr/lib/x86_64-linux-gnu -lSDL -lasound -ldl -lpng  -lm -lz
linker flags        
libavcodec (mp3)    yes
```

```
pico/cart.c:
/*
 * PicoDrive
 * (c) Copyright Dave, 2004
 * (C) notaz, 2006-2010
 *
 * This work is licensed under the terms of MAME license.
 * See COPYING file in the top-level directory.
 */

#include "pico_int.h"
#include "../cpu/debug.h"
#include "../unzip/unzip.h"
#include <zlib.h> `//this doesn't work but will if changed to #include "../zlib/zlib.h"//`
```

Why won't Picodrive build against system zlib on Ubuntu 17.04 64-bit but it will against provided zlib?  Is another target platform required for Generic Linux?

**Comment by notaz** [comment]
Pushed something that should help, reopen if it doesn't.
