### ISSUE TITLE
Puggsy cart: "Earth" in the intro animation is offset

### ISSUE THREAD

**Issue by dinkc64** [notaz/picodrive#52]
Load up Puggsy and watch the intro animation - the earth should be against the right border, but is offset.  
Here's a comparison: Picodrive: https://s1.postimg.org/ha4rv0lov/puggsy.png
Fusion: https://s1.postimg.org/ll12yyf1b/puggsyfusion.png

**Comment by notaz** [comment]
Fixed in 1.92.

**Comment by dinkc64** [comment]
I'm curious, can you please tell me what was changed to fix this?

**Comment by notaz** [comment]
I'm not sure myself, probably wrong 2cell vscroll handling.
