### ISSUE TITLE
Afterburner II psg-DAC effects missing w/info

### ISSUE THREAD

**Issue by dinkc64** [notaz/picodrive#55]
A friend noticed that the dac sounds from Afterburner II were missing w/Picodrive,
I did some debugging and noticed that the psg (sn76496) needs to be updated/rendered at least every other line per frame in order to make these effects.  You could render them every 4 lines, but there is a noticeable reduction in the quality of the dac sounds from the psg.  

best regards,
- dink ( fbalpha dev )

**Comment by notaz** [comment]
Thanks for the info, it's among many things I need to get around to fix...

**Comment by notaz** [comment]
Fixed.
