### ISSUE TITLE
Surgical Strike (CD 32X) black screen

### ISSUE THREAD

**Issue by stranno** [notaz/picodrive#57]
Brazilian copy of Sega CD 32X have been released recently and it doesnt work in any emulator.

I mean "any". Only Picodrive and Kega Fusion support Sega CD + 32X, Gens only support 32X alone.

Both Picodrive and Kega Fusion show a black screen after the Sega logo.

**Comment by notaz** [comment]
Pushed something that might help.

**Comment by stranno** [comment]
Great. Thank you notaz, can you push it to the libretro core? I cant test my RPI for now.

**Comment by notaz** [comment]
Looks like @twinaphex already merged it there.

**Comment by stranno** [comment]
Good work. It works fine as far as i played.

**Comment by stranno** [comment]
I have done three playthroughs of the game, one in Normal difficulty (2 levels of 3) and two in Hard difficulty (3 levels of 3) and it works perfectly.

So you can close the issue if you want.

Thanks again.
