### ISSUE TITLE
Dino Dini's Soccer corrupt vram cell

### ISSUE THREAD

**Issue by dinkc64** [notaz/picodrive#58]
Reproduce:
start a game of Dino Dini, when exiting to the field and enter the circle, there is a corrupt cell which appears to "animate" with data, kinda like a register values or random memory is used for the cell.
picture for reference: https://s3.postimg.org/44uuyo1df/dinodiniissue.png
It's the "character" on the right side right above the middle of the screen.

**Comment by notaz** [comment]
I'm seeing this in 1.91 but not 1.92, so I assume something fixed it.
