### ISSUE TITLE
Picodrive core slow 

### ISSUE THREAD

**Issue by DarrenBranford** [notaz/picodrive#59]
Since the latest (1.6.7) release of Retroarch, Picodrive has become very slow and , apparently, GPU intensive.

I am using a GPD XD with Legacy Rom and even Master System games are slow and laggy, only averaging around 50 - 54 fps. My device also gets unbearably hot within a matter of minutes.

Before this update, It was working perfectly fine for me.

**Comment by notaz** [comment]
This is not the core's fault, it doesn't even use the GPU, it just draws a frame purely in software.
You need to report this for the libretro fork or maybe Retroarch itself.
