### ISSUE TITLE
Collision detection doesn't exist on Star Wars for the Master System

### ISSUE THREAD

**Issue by AngieVarona** [notaz/picodrive#61]
Can't pick any items or get hit by any enemies.

![31050122-30a85368-a618-11e7-9aa4-617176c05b9d](https://user-images.githubusercontent.com/25186799/31050280-9784081e-a63d-11e7-80b9-e25a9ee5b494.png)

**Comment by notaz** [comment]
Pushed some code that might help.

**Comment by notaz** [comment]
I think it's fixed, feel free to reopen if there are still problems.

**Comment by AngieVarona** [comment]
Yes it's fixed, thanks!

Too bad I'm unable to compile the PSP version. Lots of warnings and errors..
