### ISSUE TITLE
MegaDrive SRAM not saving. 

### ISSUE THREAD

**Issue by gingerbeardman** [notaz/picodrive#64]
Saving is broken?

I'm playing [New 3D Golf Simulation: Waialae no Kiseki](https://www.segaretro.org/New_3D_Golf_Simulation:_Waialae_no_Kiseki) on Mega Drive.

If it's easier to test feel free to use the only Western release in that golf series [Pebble Beach Golf Links](https://www.segaretro.org/Pebble_Beach_Golf_Links). 

After loading the game: 
- Create Data
- Register 
- Change the name 
- End
- Press B to go out of that menu and then go back in
- You should see the saved name you previously entered

This is just one example, other things that should save in the game also do not.

Any ideas?

**Comment by notaz** [comment]
Are you sure you're on the latest version?
I can reproduce this in 1.91 but not in 1.92.

**Comment by gingerbeardman** [comment]
I'm using RetroArch on N3DS where the latest nightly only includes 1.91

https://buildbot.libretro.com/nightly/nintendo/3ds/2017-10-19_RetroArch_cia.7z

**Comment by gingerbeardman** [comment]
Today 3DS nightlies were fixed and 1.92 finally arrived! Saving works great. Thanks
