### ISSUE TITLE
Some variables and parts of game HUD not updating 

### ISSUE THREAD

**Issue by gingerbeardman** [notaz/picodrive#65]
Using latest nightly on N3DS

I'm playing [New 3D Golf Simulation: Waialae no Kiseki](https://www.segaretro.org/New_3D_Golf_Simulation:_Waialae_no_Kiseki) on Mega Drive.

If it's easier to test feel free to use the only Western release in that golf series [Pebble Beach Golf Links](https://www.segaretro.org/Pebble_Beach_Golf_Links). 

After loading the game: 
- Create Data
- Register 
- Change the name 
- End
- Start a single player tournament

Problem: 
Map shows the wrong hole map and info (this photo was taken on hole 9)

You can see a path to the left of the tee position, obviously not shown on the map.
Also a river crossing the fairway just in front of the tee position, also not on the map. 

Maps of holes:

SNES manual:
http://www.gamesdatabase.org/Media/SYSTEM/Nintendo_SNES//Manual/formated/True_Golf_Classics-_Waialae_Country_Club_-_1991_-_T-E_Soft.pdf

MegaDrive manual: 
http://www.gamesdatabase.org/Media/SYSTEM/Sega_Genesis//Manual/formated/True_Golf_Classics-_Pebble_Beach_Golf_Links_-_1994_-_Sega.pdf

![d2d90cc2-ee2e-46c1-aaab-fa39d812362c](https://user-images.githubusercontent.com/49612/31851751-ecf10e2e-b663-11e7-9a39-92fb91f07491.jpeg)

I'm using libretro nightly on N3DS

**Comment by notaz** [comment]
At the start of the game, it shows "1H" here on 1.92, and there are more markings on the map.

I guess you should wait for 1.92 builds to appear and retest before we continue on this.

**Comment by gingerbeardman** [comment]
OK

**Comment by gingerbeardman** [comment]
Having just played a few holes in  PicoDrive, it displays 1H for hole 1, 2H for hole 2 and every hole after that.

**Comment by gingerbeardman** [comment]
Using this save, which is just the initialised SRAM (otherwise it's impossible to start a game in 1.91 due to the SRAM issue) with a custom name:

there is no map or hole information shown! Marker for player position on course is shown.

[Waialae no Kiseki.defaults.zip](https://github.com/notaz/picodrive/files/1405047/Waialae.no.Kiseki.defaults.zip)

**Comment by gingerbeardman** [comment]
On reflection, I'm thinking these issues are a side-effect of invalid SRAM. 

I'll check again in 1.92 but I expect it'll work there if saving does.

**Comment by gingerbeardman** [comment]
As suspected these issues are not present in 1.92

Thanks for your work on this!
