### ISSUE TITLE
Game palette wrong and unresponsive to input after mid-game event

### ISSUE THREAD

**Issue by gingerbeardman** [notaz/picodrive#66]
Using latest nightly on N3DS

I'm playing [New 3D Golf Simulation: Waialae no Kiseki](https://www.segaretro.org/New_3D_Golf_Simulation:_Waialae_no_Kiseki) on Mega Drive.

If it's easier to test feel free to use the only Western release in that golf series [Pebble Beach Golf Links](https://www.segaretro.org/Pebble_Beach_Golf_Links). 

After loading the game: 
- Create Data
- Register 
- Change the name 
- End
- Start a single player tournament
- Complete front 9 holes 
- Dismiss "Tea Break" cut scene
- Game goes crazy 

Though oddly it does still seem to be running rather than crashing completely. 

Video: 
https://youtu.be/U9LeIUGy0D8

**Comment by notaz** [comment]
Can you provide a save state from around the time your video starts (before the "Tea Break")?

**Comment by gingerbeardman** [comment]
Yes I'll do that ASAP

**Comment by gingerbeardman** [comment]
Here it is: 
[Waialae no Kiseki.srm.zip](https://github.com/notaz/picodrive/files/1405023/Waialae.no.Kiseki.srm.zip)

To use the save:
- boot the game
- dismiss intro and start screen by pressing buttons
- at first menu choose the 2nd option
- at the next menu choose the final option
- choose the 9H save game
- confirm
- you'll have to pitch and putt to finish the whole (both shots need little power, the pale blue area, and a fairly centred red hit mark on the ball)
- if save was working the game would delete the save game from SRAM after loading it (so players can't abuse the save game system, I guess)

This save actually crashes in a more spectacular way. After "Tea Break" you get the leaderboards and the score is -2000 or something, and the game gets in a loop of instantly finishing each hole on the first 9, getting to tea break and then doing the loop all over again.

I expect behaviour is slightly different than before because it's resumed from save?

I tried making a save state, but the 1.91 core crashes at 87% loading it. let me know if you want it.

**Comment by gingerbeardman** [comment]
This is also resolved in 1.92 thanks to saving now working. Thanks!

**Comment by gingerbeardman** [comment]
I just finished my first 18 holes :)

x400% overclock is an awesome feature, makes the game feel really modern with quick redraws
