### ISSUE TITLE
[32x] SH2: Illegal opcode at 06000ce8 

### ISSUE THREAD

**Issue by retro-wertz** [notaz/picodrive#67]
Using the libretro port here. when running a 32x game, specifically NBA JAM Tournament Edition 32x, the game will cause illegal opcode after about 1-2 minutes.

Step to reproduce.
1. Load NBA JAM Tournament Edition 32x and let demo run.

![screenshot_2017-10-22_06-57-40](https://user-images.githubusercontent.com/23315382/31856553-698bd1ca-b6f6-11e7-8d04-e006bc4aae8e.png)

**Comment by notaz** [comment]
I've just pushed fixes for this, including the ARM dynarec.

**Comment by Tasosgemah** [comment]
Issue still exists in version 1.99
