### ISSUE TITLE
./configure problems

### ISSUE THREAD

**Issue by cratty79** [notaz/picodrive#69]
When I run ./configure I get an error message saying to run "git submodule update --init" but then I run that it says "Fatal: Not a git repository (or any of the parent directories): .git" and I was wondering why that is.

**Comment by notaz** [comment]
How do you retrieve the main source then, not with git?

**Comment by cratty79** [comment]
I downloaded the main branch through the "Clone" dropdown first but then I went through git. There is not a .git folder or file in the main source.

**Comment by notaz** [comment]
No idea how you manage not to get ".git". Can you show you commands? Mine are:
> $ git clone https://github.com/notaz/picodrive.git
> Cloning into 'picodrive'...
> ...
> $ cd picodrive/
> $ ls -ld .git
> drwxrwxr-x 8 notaz notaz 4096 Nov 12 18:01 .git

**Comment by cratty79** [comment]
It seems to have downloaded on Windows git, but not the git on my Raspberry Pi, which I last tested yesterday, so when I get home, I'll test it.

**Comment by cratty79** [comment]
It works, I had to unhide everything in my file manager then run it in the terminal, which is weird.
