### ISSUE TITLE
A graphical issue using accurate renderer

### ISSUE THREAD

**Issue by robson-alcantara** [notaz/picodrive#71]
Retroarch (picodrive 1.91 core)
![retroarch](https://user-images.githubusercontent.com/20538912/33156205-91df18c0-cfde-11e7-99c7-7aeacf5ad200.png)

Kega Fusion
![fusion](https://user-images.githubusercontent.com/20538912/33156211-9fb9e718-cfde-11e7-8689-c789bc779461.png)

**Comment by notaz** [comment]
Fixed.
