### ISSUE TITLE
release tarballs

### ISSUE THREAD

**Issue by orbea** [notaz/picodrive#82]
I would like to switch `picodrive-libretro` at slackbuilds.org (Slackware packages) to `picodrive` which will include both the standalone emulator and the libretro core. It would be best to use the stable release tarballs. However the auto generated tarballs github provides lack the submodules and are not suitable to building the standalone version of picodrive. Would it be possible to make this easier for package maintainers?

Here are some ideas.

1. Provide manually created release tarballs in `.tar.gz`, `.tar.bz2` and/or `.tar.xz` format that include the submodules.
2. Remove the git submodules and add them back as git subtrees so github's tarballs will include them. This has many other benefits as well and I can make a PR doing this if desired.
3. I continue generating my own tarballs of arbitrary commits as I have been doing for `picodrive-libretro`

Thanks!

**Comment by orbea** [comment]
@notaz I'll take the silence as a won't fix...only people with push access can upload tarballs to github so I can't send a PR to fix this.

**Comment by notaz** [comment]
I think I simply forgot this, sorry. I can do it if it still helps you.

**Comment by orbea** [comment]
Yes, it would be helpful. Currently I have to generate my own tarballs with the missing submodules which is not ideal as not everyone may trust the tarballs I make as much as they would from the developer of the program. :)

**Comment by notaz** [comment]
Done, hope that works for you.

**Comment by orbea** [comment]
Yes that works for me, thank you! I've sent an updated build script for 1.93 to slackbuilds.org which should be merged sometime this weekend.
